//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork.Regular_Employee {
	
	
	public partial class Tasks {
		
		protected System.Web.UI.HtmlControls.HtmlForm ProjectsForm;
		
		protected System.Web.UI.WebControls.Label usernameLbl;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton2;
		
		protected System.Web.UI.WebControls.GridView tasks;
		
		protected System.Web.UI.WebControls.Button Fix;
		
		protected System.Web.UI.WebControls.Button Assgin;
	}
}
