//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork {
    
    
    public partial class Login {
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.WebControls.Label lbl_username;
        
        protected System.Web.UI.WebControls.TextBox txt_username;
        
        protected System.Web.UI.WebControls.Label lbl_password;
        
        protected System.Web.UI.WebControls.TextBox txt_password;
        
        protected System.Web.UI.WebControls.Button btn_login;
    }
}
