//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork.Manager.Profile.templates {
	
	
	public partial class Manager_Selected_Project {
		
		protected System.Web.UI.HtmlControls.HtmlForm ProjectsForm;
		
		protected System.Web.UI.WebControls.GridView RegEmpView;
		
		protected System.Web.UI.WebControls.Button AddToProject;
		
		protected System.Web.UI.WebControls.Button RemoveFromProject;
	}
}
