//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork.Manager.Profile.templates {
    
    
    public partial class Manager_Projects {
        
        protected System.Web.UI.HtmlControls.HtmlForm ProjectsForm;
        
        protected System.Web.UI.WebControls.GridView MyProjectsView;
        
        protected System.Web.UI.WebControls.Button SelectProject;
        
        protected System.Web.UI.WebControls.TextBox ProjectNametxt;
        
        protected System.Web.UI.WebControls.TextBox TextBox1;
        
        protected System.Web.UI.WebControls.TextBox TextBox2;
        
        protected System.Web.UI.WebControls.Button CreateProject;
    }
}
