//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork.Manager {
	
	
	public partial class Manager_Requests_Review {
		
		protected System.Web.UI.HtmlControls.HtmlForm ProjectsForm;
		
		protected System.Web.UI.WebControls.Label usernameLbl;
		
		protected System.Web.UI.WebControls.TextBox Reasontxt;
		
		protected System.Web.UI.WebControls.Button AcceptRequest;
		
		protected System.Web.UI.WebControls.Button RejectRequest;
	}
}
