//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork.Manager {
	
	
	public partial class Manager_Review_Task {
		
		protected System.Web.UI.HtmlControls.HtmlForm ProjectsForm;
		
		protected System.Web.UI.WebControls.Label usernameLbl;
		
		protected System.Web.UI.WebControls.TextBox projectNameforTaskTxt;
		
		protected System.Web.UI.WebControls.TextBox statusTxt;
		
		protected System.Web.UI.WebControls.Button SearchForTask;
		
		protected System.Web.UI.WebControls.GridView SearchForTaskView;
		
		protected System.Web.UI.WebControls.Button AcceptTask;
		
		protected System.Web.UI.WebControls.Button RejectTask;
	}
}
