//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork.Manager {
	
	
	public partial class Manager_Project_Task {
		
		protected System.Web.UI.HtmlControls.HtmlForm TasksForm;
		
		protected System.Web.UI.WebControls.TextBox TaskNametxt;
		
		protected System.Web.UI.WebControls.TextBox descriptiontxt;
		
		protected System.Web.UI.WebControls.TextBox deadline;
		
		protected System.Web.UI.WebControls.Button CreateTask;
		
		protected System.Web.UI.WebControls.GridView MyTasksView;
		
		protected System.Web.UI.WebControls.Button SelectTask;
	}
}
