//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork.Manager {
	
	
	public partial class Manager_Projects {
		
		protected System.Web.UI.HtmlControls.HtmlForm ProjectsForm;
		
		protected System.Web.UI.WebControls.TextBox ProjectNametxt;
		
		protected System.Web.UI.WebControls.Calendar Calendar1;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton1;
		
		protected System.Web.UI.WebControls.TextBox TextBox1;
		
		protected System.Web.UI.WebControls.Calendar Calendar2;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton2;
		
		protected System.Web.UI.WebControls.TextBox TextBox2;
		
		protected System.Web.UI.WebControls.Button CreateProject;
	}
}
