//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork.Manager {
	
	
	public partial class Manager_Requests {
		
		protected System.Web.UI.HtmlControls.HtmlForm ProjectsForm;
		
		protected System.Web.UI.WebControls.GridView RequestsGridView;
		
		protected System.Web.UI.WebControls.Button SelectRequest;

        protected System.Web.UI.WebControls.Button TypeOfRequest;

    }
}
