//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWork.Regular_Employee {
	
	
	public partial class Regular_Employee {
		
		protected System.Web.UI.HtmlControls.HtmlForm ProjectsForm;
		
		protected System.Web.UI.WebControls.Label usernameLbl;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton2;
        protected System.Web.UI.WebControls.DataList DataList1;

        protected System.Web.UI.WebControls.DropDownList yofexp;
        protected System.Web.UI.WebControls.DropDownList day;
        protected System.Web.UI.WebControls.DropDownList Month;
        protected System.Web.UI.WebControls.DropDownList Year;
        protected System.Web.UI.WebControls.TextBox fn;
        protected System.Web.UI.WebControls.TextBox ln;
        protected System.Web.UI.WebControls.TextBox mn;
        protected System.Web.UI.WebControls.TextBox email;
        protected System.Web.UI.WebControls.GridView Previous;
        protected System.Web.UI.WebControls.TextBox pass;
        protected System.Web.UI.WebControls.TextBox new_previous;
    }
}
